### ISSUE TITLE
Resultados diferentes

### ISSUE THREAD

**Issue by Oxicode** [richardforth/apache2buddy#23]
![apache](https://cloud.githubusercontent.com/assets/1320709/20893715/bf0e33f8-bae0-11e6-91bb-bbf08cddffaf.gif)

**Comment by richardforth** [comment]
Hi,

Yes the results will be different if youve just restarted apache, This is normal behaviour,

You need to let the applications bed in, and consume memory before tuning it. You cant realistically tune ana apache server that has just been restarted

**Comment by richardforth** [comment]
This is not a bug, but I have decided to re-open it as this needs some clarification.

1. When apache first starts, or is restarted, all the assigned memory is dropped, so running apache2buddy right after a restart will NOT give you the same results as if yo uran it after say 24 hours or more of operation, memory leaks in the application itself (not apache2buddy, the web application) or apache, can cause memory bloating over time, restarting apache clears all this down, so, in your case, yes apache2buddy would hve recommended 40 maxclients, but after a period of use, teh memory bloat means that the recommendation changes to reflect the actual usage, recommending 16. 

When you restart apache you clear off all the memory bloat caused by the apache server running in, and now apache2buddy recommends 40 again.

I have therefore decided to address this issue in a couple of possible ways:

1. Have apache2buddy exit abruptly if the uptime is less than 1 hour, with a recommedation to run again after 24 hours of continuous operation.

If apache has an uptime of between 1 hour and 24 hours, have apache2buddy warn that the following recommendations may be misleading as apache has only just been restarted within the last 24 hours. 

or

2. If apache has an uptime of less than 24 hours, have apache2buddy warn that the following recommendations may be misleading as apache has only just been restarted within the last 24 hours. 

I havent decided which one to go with, but most likely option 2.

**Comment by richardforth** [comment]
My current thoughts on how to handle this:

If apache has an uptime of less than 24 hours, have apache2buddy warn something like this:

[ WARNING ] *** LOW UPTIME ***
[ ADVISORY ] The following recommendations may be misleading as apache has only just been restarted within the last 24 hours. 

The check would be fairly easy as we just need to check that “days = 0”  since there’s no larger number to worry about, eg:

[ INFO ] Apache has been running 0d 0h 44m 54s.

**Comment by richardforth** [comment]
![image](https://cloud.githubusercontent.com/assets/5919831/20933629/8f022be2-bbd0-11e6-8e16-37e84176f9b8.png)

**Comment by richardforth** [comment]
![image](https://cloud.githubusercontent.com/assets/5919831/20933696/cd377d18-bbd0-11e6-956e-3c8627f4ac72.png)

**Comment by richardforth** [comment]
![image](https://cloud.githubusercontent.com/assets/5919831/20933737/e207b9c4-bbd0-11e6-9d63-5fc3c6347fc7.png)

**Comment by richardforth** [comment]
changes pushed live, from staging
