### ISSUE TITLE
Fedora ?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [richardforth/apache2buddy#256]
[ -- ] Distro: Fedora
[ -- ] Version: 27
[ -- ] Codename: Twenty Seven
[ !! ] This distro is not supported by apache2buddy.pl.

I tried to use --skip-os-version-check but this option does not exist...
any clue?
thanks

**Comment by ROBERT-MCDOWELL** [comment]
well, I just simple disagree about Fedora, I'm using it as server since 15 years now
without any production issue. It's an old opinion to say Fedora is not better than Cent OS or other red hat like...

**Comment by richardforth** [comment]
Hi Robert,

Thanks for your response, I do understand your concerns however I do not intend on including Fedora support in any future versions on apache2buddy.

Regarding the --skip-os-version-check, this option hasnt yet been implemented, I raised it as an issue to aid in circumstances like these to save editting the code manually but it still only a conceptual idea, raised in https://github.com/richardforth/apache2buddy/issues/245

Regarding Fedora, I do see they now have a 'Fedora Server' option, which is a big change since i last used it, however the relationship between Fedora and RHEL/CentOS remains as one of bleeding edge versus stability:

https://www.redhat.com/en/technologies/linux-platforms/articles/relationship-between-fedora-and-rhel

And so for that reason (and the fact that apache2buddy is already close to if not over 3000 lines of code  - just to make it work across debian, ubuntu, RHEL, and CentOS.

It is really frustrating I know and I had hoped to implement #245 to help with this but I havent had a lot of free time to develop this project recently.

As I said the issue is that apache2buddy is completely untested on Fedora so I cannot guarrantee it will work even once you amend the following code (as I am now at a computer I can show you the lines you'll need to modify):

Line 325 - 335:

```perl
my @supported_os_list = ('Ubuntu',
				'ubuntu',
				'Debian',
				'debian',
				'Red Hat Enterprise Linux',
				'Red Hat Enterprise Linux Server',
				'redhat',
				'CentOS Linux',
				'CentOS',
				'centos',
				'Scientific Linux');
```

You'd need to change this list to include Fedora:

```perl
my @supported_os_list = ('Ubuntu',
				'ubuntu',
				'Debian',
				'debian',
				'Red Hat Enterprise Linux',
				'Red Hat Enterprise Linux Server',
				'redhat',
				'CentOS Linux',
				'CentOS',
				'centos',
				'Scientific Linux',
                                 'Fedora');
```

Line 344:

```perl
my @redhat_os_list = ('Red Hat Enterprise Linux', 'redhat', 'CentOS Linux', 'Scientific Linux');
```

This is a list of allowed strings for the OS version, according to your specific output, you'd need to change this to:

```perl
my @redhat_os_list = ('Red Hat Enterprise Linux', 'redhat', 'CentOS Linux', 'Scientific Linux', 'Fedora');
```

I believe that '27' should be fine (see lines 384 to 401), and the codename doesn't matter at all regarding support checks.

Again though, please note that making these changes doesn't make Fedora "Supported" It just tricks the code into passing that particular check, it may break and do weird things that are unexpected. So you do this and run it at your own risk.

If you compile your own apache from source this is also unsupported and again may break the script. The script realy only supports the packaged software from YUM repositories. It doesnt support DNF yet either - so you may have to modify additional code:

Check the function at Line 2038, paying particular attention to line 2044:

```perl
$package_update = `yum check-update | egrep "^httpd|^php"`;
```

Since I dont work on DNF enabled systems I am not sure what this should be, but a guess would be:

```perl
$package_update = `dnf check-update | egrep "^httpd|^php"`;
```

This assumes dnf is a drop-in replacement for yum, you may need to adjust this to suit your needs.

DNF Is something I know is coming in RHEL8 (and therefore CentOS8), so it is on my todo list and has already been raised as issue #237.

As I mentioned previously I'm struggling to find the time to work on development at this time, and because apache2buddy has to be backward compatible to support currently supported versions of RHEL/CentOS that use yum, its not simply a case of changing yum to dnf, I'd have to put additional logic in place to check the exact redhat version and / or check for the precence of yum or dnf executables before deciding which path to take. 

Though it sounds incredibly straightforward, it causes a lot of testing across all the distros currently supported to ensure it hasnt broken anything. Adding another distro like Fedora to that list adds to that pain, #245 was supposed to solve that (when I get round to it) however, as we've already discussed, the DNF issue is likely to break the script anyway.

I really do appreciate your feedback and I hope that this is reflected in the length and depth of my reply.  I do encourage you to fork your own copy and make adjustments to suit your own needs, because as I say my 'official' support offering is strictly limited to Ubuntu LTS versions, Debian, Red Hat Enterprise Linux, and CentOS.

I hope my advice allows you to run apache2buddy on your Fedora systems and if you need any advice you can respond here and when I can I'll offer any suggestions to help you get it working.

Kind Regards
Richard

**Comment by ROBERT-MCDOWELL** [comment]
thanks for all Richard, I forked and will do some PR when have time.
