### ISSUE TITLE
CloudLinux not supported

### ISSUE THREAD

**Issue by timrutter** [richardforth/apache2buddy#26]
Errors with "[ CRITICAL ] Either we couldnt get the OS name, or its not a supported distro."

As CloudLinux is based upon Centos Ive created this diff

```
*** 1333,1336 ****
--- 1333,1338 ----
  	        if ( $os_name eq "CentOS" ) {
  		        $os_release = `cat /etc/redhat-release 2>&1 | head -1 | awk '{ print \$3 }'`;
+        		 } elsif ( $os_name  eq "CloudLinux" ) {
+ 		        $os_release = `cat /etc/redhat-release 2>&1 | head -1 | awk '{ print \$3 }'`;
         		 } elsif ( $os_name  eq "Red" ) {
  	        	$os_name = `cat /etc/redhat-release 2>&1 | head -1 | awk '{ print \$1 " " \$2 " " \$3 " " \$4 }'`;

```
Now passes OS check

**Comment by richardforth** [comment]
Hi

Thanks.

Can you please make a pull request from staging and I'll get this promoted
in the next update.

**Comment by timrutter** [comment]
Wow your fast 👍 

found another edit
Stops again on 
[ INFO     ] pidfile setting is /usr/local/apache/logs/httpd.pid.
[ CRITICAL ] Unable to open pid file /var/run/httpd/httpd.pid. Exiting.


*** 1629,1632 ****
--- 1631,1637 ----
  		} elsif ($pidfile_cfv eq "/var/run/apache2\$SUFFIX.pid") {
  			our $pidfile = "/var/run/apache2.pid";
+ 		} elsif ($pidfile_cfv eq "/usr/local/apache/logs/httpd.pid") {
+ 			# For CloudLinux
+ 			our $pidfile = "/usr/local/apache/logs/httpd.pid";
  		} else {
  			# set default (works on CentOS7)

**Comment by richardforth** [comment]
Heh no problems

Sounds good,  add it to the pull request. please pull from staging.

Kind Regards
Richard

On 12 Dec 2016 01:23, "timrutter" <notifications@github.com> wrote:

Wow your fast 👍

found another edit
Stops again on
[ INFO ] pidfile setting is /usr/local/apache/logs/httpd.pid.
[ CRITICAL ] Unable to open pid file /var/run/httpd/httpd.pid. Exiting.

*** 1629,1632 ****
--- 1631,1637 ----
} elsif ($pidfile_cfv eq "/var/run/apache2$SUFFIX.pid") {
our $pidfile = "/var/run/apache2.pid";

   -

     } elsif ($pidfile_cfv eq "/usr/local/apache/logs/httpd.pid") {

   -

     	# For CloudLinux

   -

     	our $pidfile = "/usr/local/apache/logs/httpd.pid";
     } else {
     	# set default (works on CentOS7)


—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/richardforth/apache2buddy/issues/26#issuecomment-266324094>,
or mute the thread

**Comment by richardforth** [comment]
Hi,

I've had a day or two to think this over and I wanted to say that while I thank you for your contribution, and will try to incorporate your charges as much as possible it is really important to note that CloudLinux insnt going to be supported.

The main reason that CloudLinux is not supported is that its not an available distro for me to test on in my cloud environment.

Only the following Linuxes are currently supported:

CentOS 5, 6, 7
RHEL, 5, 6, 7
Debian 6,7,8
Ubuntu 12.04 14.04 16.04

I dont have CloudLinuc available to test on, hence, i cant guarrantee 100% that any features i add in the future will be 100% compatible, so instead of the "This OS is supported" message, youre more likely to see "This distro is not supported, you may get errors". 

At least this way it still runs but you just get the warning that it may not be 100% compatible.

You might disagree but as a one man band I have to draw the line at how much testing I do on each release, i don't have a huge Jenkins setup or anything, its just me and my cloud, 

I appreciate that you mentioned that CloudLinux is based on CentOS. but its clearly still different, and also not available as a testing distro for me, Hence the lack of support.

I also don't support any custom  / compiled apache installations, such as those with cPanel or anythign compiled from source, I only support the packages available from the main software channels. Youve seen the code that I integrated for someone else, regarding cPanel, so Im happy to try and integrate yours too, but again cPanel isnt part of my testing, and it never will, because its licensed software, I keep my costs low by hosting on github and spinning up only the servers I need to complete my tests.

Again I just want to empasise that I'll accommodate you as much as possible, but there is a reason why CloudLinux isnt supported.

Even if I wasnt so accomodating, the cool dthing about open Source is you can fork this and do with it as you wish for your own use. Just don't forget that its now Licensed under the Apache 2.0 License (its a pretty flexible license but you should read it all the same).

Regarding the changes, please can you make a pull request from Staging, if you havent already, so that I can merge the changes in staging, and do any necessary changes and tweaks,, and then I'll promote it to live as soon as I can.

Changes mainly occurr on evenings and weekends as and when i have time, though its running up to christmas so i have less free time than usual, there is a critical update regarding php-fpm error logs that I need to get in soon, so i can roll it all up into that.

Hope that explains the situation 

Kind Regards
Richard
