### ISSUE TITLE
apachectl location on cPanel

### ISSUE THREAD

**Issue by timrutter** [richardforth/apache2buddy#27]
Have been running apache2buddy.pl with PATH to run on cPanel/WHM hosts.
`PATH=/usr/local/apache/bin/:$PATH ./apache2buddy.pl`

The following adds cPanel's apache path to the apachectl lookup internally
```
*** 1285,1289 ****
  	# Check for which apachectl we are to use
  	# check to see if there is a binary called "apachectl" in our path
- 	our $apachectl= `which apachectl`;
+	our $apachectl= `PATH=/usr/local/apache/bin/:\$PATH which apachectl`;
  	chomp($apachectl);

```

**Comment by richardforth** [comment]
Hi Tim.

Thanks for the update, just to let you know (as per my update on your other issue):

I  don't support any custom / compiled apache installations, such as those with cPanel or anything compiled from source, I only support the packages available from the main software channels. Youve seen the code that I integrated for someone else, regarding cPanel, so Im happy to try and integrate yours too, but again cPanel isnt part of my testing, and it never will, because its licensed software, I keep my costs low by hosting on github and spinning up only the servers I need to complete my tests.

Again I just want to empasise that I'll accommodate you as much as possible, but there is a reason why cpanel and comiled form source apache isnt supported. (note that the apache installation that cpanel provides is deployed to /usr/local/apache which is a default location for compiled software.

Even if I wasnt so accomodating, the cool dthing about open Source is you can fork this and do with it as you wish for your own use. Just don't forget that its now Licensed under the Apache 2.0 License (its a pretty flexible license but you should read it all the same).

Regarding the changes, please can you make a pull request from Staging, if you havent already, so that I can merge the changes in staging, and do any necessary changes and tweaks,, and then I'll promote it to live as soon as I can.

Changes mainly occurr on evenings and weekends as and when i have time, though its running up to christmas so i have less free time than usual, there is a critical update regarding php-fpm error logs that I need to get in soon, so i can roll it all up into that.

Hope that explains the situation, and I look forward to seeing your pull request soon.

Kind Regards
Richard
