### ISSUE TITLE
grep for root fails

### ISSUE THREAD

**Issue by BlueFishey** [richardforth/apache2buddy#324]
I run a Remi dist for my Apache so it has root in the path to binary as well as root running process 

Was 
    860         # get a list of the pid's for apache running as the appropriate user
    861         my @pids = `ps aux | grep $process_name | grep -v root | grep $apache_user | awk \'{ print \$2 }\'`;

Now 
    860         # get a list of the pid's for apache running as the appropriate user
    861         my @pids = `ps aux | grep $process_name | grep -v "^root" | grep $apache_user | awk \'{ print \$2 }\'`;

Peachy :)

**Comment by richardforth** [comment]
Oh cool,

Thanks for your suggestion, I understand your predicament and the change
makes sense

If you fork it from staging and make a PR I can merge it, In order to do
that I need the following in addition to the code change:

1. Update the changelog, add the date, your name (or GiHub Handle ) (and be
immortalized as a contributor to the project) and a bit about the change,
following the same format of the changelog)

2. Create new md5sums

eg "md5sum apache2budd.pl > md5sums.txt"

3. Create new sha256sums

eg "sha256sum apache2buddy.pl > sha256sums.txt"

This should result in 4 files for the PR:

apache2buddy.pl
changelog
md5sums.txt
sha256sums.txt

This makes it much easier to merge PRs (the checksums are used in
automation, and if they dont match, it breaks the automation (fail-safe))

If youre not comfortable with the above, i will do it, and give you the
credit. I really appreciate your contribution

If you would be so kind I would also really benefit if you can start my
project also :)

Thanks for your interest and for helping apache2buddy.pl be better!

Kind Regards
Richard

**Comment by richardforth** [comment]
this might be resolved in a new pull request that was merged into staging, try this:

```bash
curl https://raw.githubusercontent.com/richardforth/apache2buddy/staging/apache2buddy.pl | perl
```
Im doing testing before pushing it live. let me know if the fix works in staging please.

Sorry updates are slow here, im a one man band with a full time job.

I appreciate your patience.

Kind regards
Richard

**Comment by richardforth** [comment]
A recent merge may have solved this, we are no longer `grep -v root` ing this:

https://github.com/richardforth/apache2buddy/blob/1ce6aa8610dbde1d232fec5920ec9ff800911bdd/apache2buddy.pl#L861

```perl
my @pids = `ps aux | grep $process_name | grep "^$apache_user\\s" | awk \'{ print \$2 }\'`;
```

I believe this resolves your issue  so I will mark it as closed, however if you don't find it has been fixed, please re-open it.
